
PREFIX = powerpc-eabi-

ifeq ($(OS),Windows_NT)
	BIN2H = ../bin2h/bin2h.exe
else
	BIN2H = ../bin2h/bin2h
endif

ifeq ($(high), 1)
	LDSCRIPT = cubehigh.ld
	TARGET_TMP = loader_cube_high.bin
	TARGET = loader_cube_high.h
	DEFINES = -DHIGH=1
else
	LDSCRIPT = cube.ld
	TARGET_TMP = loader_cube.bin
	TARGET = loader_cube.h
	DEFINES = -DLOW=1
endif

AR = $(PREFIX)ar
AS = $(PREFIX)as
CC = $(PREFIX)gcc
CXX = $(PREFIX)g++
LD = $(PREFIX)ld
OBJCOPY = $(PREFIX)objcopy
RANLIB = $(PREFIX)ranlib
STRIP = $(PREFIX)strip

MACHDEP = -mcpu=750 -mno-eabi -mhard-float -DHW_DOL=1

# Errors? What errors?
#CFLAGS = $(MACHDEP) -O2 -Werror -Wall

CFLAGS = $(MACHDEP) -O2
LDFLAGS = $(MACHDEP) -n -nostartfiles -nostdlib -Wl,-T,$(LDSCRIPT) -L.
ASFLAGS = -DHW_DOL=1 -D_LANGUAGE_ASSEMBLY

TARGET_LINKED = loader.elf
TARGET_DOL = loader.dol

OBJS = crt0.o cache_asm.o exception_handler.o system_asm.o argv.o main.o xz_crc32.o xz_dec_bcj.o xz_dec_lzma2.o xz_dec_stream.o 

DEPDIR = .deps

LIBS = 

all: $(TARGET)

%.o: %.s
	@echo " ASSEMBLE    $<"
	$(CC) $(CFLAGS) $(DEFINES) $(ASFLAGS) -c $< -o $@

%.o: %.S
	@echo " ASSEMBLE    $<"
	$(CC) $(CFLAGS) $(DEFINES) $(ASFLAGS) -c $< -o $@

%.o: %.c
	@echo " COMPILE     $<"
	$(CC) $(CFLAGS) $(DEFINES) -c $< -o $@

loader.elf: $(OBJS)
	@echo " LINK        $@"
	$(CC) -g -o $@ $(LDFLAGS) $(OBJS) $(LIBS)

loader.dol: loader.elf
	@echo " ELF2DOL     $@"
	elf2dol $< $@

$(TARGET): loader.dol
	@echo " BIN2H       $@"
	mv $< $(TARGET_TMP)
	$(BIN2H) $(TARGET_TMP)
	mv $(TARGET_TMP) $<

clean:
	rm -rf loader.elf loader.dol $(TARGET) $(OBJS) $(DEPDIR)
